### ISSUE TITLE
Update README

### ISSUE THREAD

**Issue by Nitinrajyadav** [foundeo/cfml-compiler#1]
What are the goals and plans for this project? I was exploring options to compile CFML and hopefully, possibilities to create some tools like webpack, babel etc.

**Comment by pfreitag** [comment]
Hi @Nitinrajyadav - right now the main goal of the project is to be able to take CFML files and compile them into class files. You can then replace your cfm / cfc files with the corresponding compiled cfm / cfc files. This is useful when using with fuseless.org (lamda) or when building docker containers. I will update the readme with some more info as well.
