### ISSUE TITLE
Files created using --overwrite throw exceptions

### ISSUE THREAD

**Issue by chapmandu** [foundeo/cfml-compiler#7]
Running an application compiled using the --overwrite flag causes the exception below. Though using files created using a different source and dest directory works as expected.

Below is all the information I can gather.

Environment:
Application Lucee Version: 5.3.5.92
OS: Ubuntu 19.10
CommandBox 5.0.1+00137

Command:
`box compile source=./build/ --overwrite cfengine=lucee@5.3.5.92`

Commandbox output:
```
Compiling ./build...
 √ | Starting Server
   | √ | Installing package [forgebox:lucee@5.3.5.92]
Starting RunWAR 4.0.5
Java version 1.8.0.202 (requires >= 1.8)
HTTP2 Enabled:false
HTTP sslEnable:false
HTTP ajpEnable:false
HTTP warFile exists:true
HTTP warFile isDirectory:true
Starting background cfml-compiler-server [lucee 5.3.5+92] from: /home/adam/.CommandBox/lib/runwar-4.0.5.jar 
Starting in background -
Starting compilation of: /home/adam/code/valy/www/myapp/build/
Destination: /home/adam/code/valy/www/myapp/build/
Finished!
Stopping cfml-compiler-server...
Stopped
forgetting cfml-compiler-server...
Poof! Wiped out server cfml-compiler-server
```

Exception message when running compiled code:
```
Bad type on operand stack
Exception Details:
Location:
com/amazonaws/services/s3/AmazonS3Client.putObject(Lcom/amazonaws/services/s3/model/PutObjectRequest;)Lcom/amazonaws/services/s3/model/PutObjectResult; @2: invokevirtual
Reason:
Type 'com/amazonaws/services/s3/model/PutObjectRequest' (current frame, stack[1]) is not assignable to 'com/amazonaws/AmazonWebServiceRequest'
Current Frame:
bci: @2
flags: { }
locals: { 'com/amazonaws/services/s3/AmazonS3Client', 'com/amazonaws/services/s3/model/PutObjectRequest' }
stack: { 'com/amazonaws/services/s3/AmazonS3Client', 'com/amazonaws/services/s3/model/PutObjectRequest' }
Bytecode:
...
```

AWS SDK 1.11.574
SDK invoked using lucee https://github.com/mso-net/lucee-aws

Thanks for this amazing module!

**Comment by chapmandu** [comment]
I have a feeling it's something to do with the location of aws.jar. When I move it from `/lib/aws.jar` (mapping) to `/WEB-INF/lib/aws.jar` the exception doesn't occur.

**Comment by pfreitag** [comment]
Ok - good to know, will have to look into it further. 

How are you using the aws.jar is it just `createObject()` or what?

**Comment by pfreitag** [comment]
When you say `/lib/aws.jar` is a mapping, do you mean that you have it defined in `Application.cfc` via `this.javaSettings`?

**Comment by chapmandu** [comment]
Yes using createObject. The exception points to this line.

https://github.com/mso-net/lucee-aws/blob/master/aws.cfc#L50

And also yes the mapping is created as below.

this.javasettings = {
	loadPaths = [
		"/lib/"
	]
};

Hope this helps.

**Comment by pfreitag** [comment]
Thanks - I wonder if it is due to the relative path "/lib/" in your load paths. I'm curious if you change that line to: `loadPaths = [ getDirectoryFromPath( getCurrentTemplatePath() ) & "lib/" ]` if it then works.

**Comment by bdw429s** [comment]
If you compare the compiled code with and without the jar on the classpath, is Lucee generating different bytecode in the absence of the jar at compile time?  Maybe compare the exact size of the file or decompile both files to compare the code.

**Comment by chapmandu** [comment]
It was indeed the relative `/lib/` load path. Using the explicit path resolved my problem. Thanks for a great tool!
